# fly.toml app configuration file generated for jobe on 2023-09-09T17:49:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jobe"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 4
  processes = ["app"]
